In [94]:
cd pandas/

[Errno 2] No such file or directory: 'pandas/'
/home/patanjalichanakya/Documents/denver/dsi/pandas


In [95]:
import pandas as pd
from numpy.random import randn
import numpy as np

#Numpy

In [96]:
x = np.arange(10)
print x
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
print x
print x[:3]  # Get the first three elements
print x[-3:] # Get the last three elements
print x[1:4] # Get some elements in the middle

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[7 8 9]
[1 2 3]


In [98]:
print x[::-2] # Get every second element
print x[::3] # Get every third element

[9 7 5 3 1]
[0 3 6 9]


In [99]:
x1 =x.reshape(2,5)
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
x1[:,1]

array([1, 6])

In [101]:
x1[1,2:4]

array([7, 8])

In [102]:
x1[:,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [103]:
x1[:,:-2]

array([[0, 1, 2],
       [5, 6, 7]])

#Pandas

##What is Pandas?
A Python library providing data structures and data analysis tools.

Think of it like Excel for Python that doesn't suck.

# Series 
hink of a Pandas Series as a _labeled_ one-dimensional vector. In fact, it need not be a numeric vector, it can contain arbitrary python objects.

In [104]:
int_series = pd.Series(range(10))
int_series

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

#Indexes.
Notice how each series has an index (in this case a relatively meaningless default index).

Pandas can make great use of informative indexes. Indexes work similarly to a dictionary key, allowing fast lookups of the data associated with the index.

Indexes can also be exploited for fast group-bys, merges, time-series operations and lots more.

When you're really in the zone with pandas, you'll be thinking a lot about indexes.

In [105]:
int_series_index = pd.Series(range(10), index = ['California', 'Alabama', 
                                    'Indiana', 'New York', 
                                    'Kentucky']*2)
int_series_index

California    0
Alabama       1
Indiana       2
New York      3
Kentucky      4
California    5
Alabama       6
Indiana       7
New York      8
Kentucky      9
dtype: int64

In [106]:
print int_series_index.order(ascending=False)

Kentucky      9
New York      8
Indiana       7
Alabama       6
California    5
Kentucky      4
New York      3
Indiana       2
Alabama       1
California    0
dtype: int64


In [107]:
int_series + int_series_index

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
Alabama      NaN
Alabama      NaN
California   NaN
California   NaN
Indiana      NaN
Indiana      NaN
Kentucky     NaN
Kentucky     NaN
New York     NaN
New York     NaN
dtype: float64

In [108]:
int_series_index_random = pd.Series(randn(10), index = ['California', 'Alabama', 
                                    'Indiana', 'Montana', 
                                    'Kentucky']*2)
int_series_index_random

California    0.772792
Alabama      -1.026277
Indiana      -0.216992
Montana       1.162989
Kentucky     -1.100127
California   -1.876995
Alabama      -0.778947
Indiana      -0.231247
Montana      -1.391360
Kentucky      0.451357
dtype: float64

In [109]:
int_series_index_random + int_series_index

Alabama      -0.026277
Alabama       4.973723
Alabama       0.221053
Alabama       5.221053
California    0.772792
California    5.772792
California   -1.876995
California    3.123005
Indiana       1.783008
Indiana       6.783008
Indiana       1.768753
Indiana       6.768753
Kentucky      2.899873
Kentucky      7.899873
Kentucky      4.451357
Kentucky      9.451357
Montana            NaN
Montana            NaN
New York           NaN
New York           NaN
dtype: float64

In [110]:
indexed_series = pd.Series(randn(5*10), 
                           index = ['California', 'Alabama', 
                                    'Indiana', 'Montana', 
                                    'Kentucky']*10)
#If you have non-unique indexes, you can use them 
#to do groupby operations.
print indexed_series
indexed_series.groupby(level=0).mean()

California   -0.428807
Alabama       0.565460
Indiana      -0.193586
Montana      -0.055350
Kentucky      1.363124
California   -1.387987
Alabama      -2.120202
Indiana      -1.143089
Montana       0.114854
Kentucky     -0.368977
California    0.385074
Alabama       0.892126
Indiana      -0.500754
Montana      -0.813651
Kentucky      0.493459
California    0.904490
Alabama       1.346195
Indiana       0.812234
Montana      -0.168281
Kentucky     -0.345427
California   -2.219293
Alabama      -0.117989
Indiana       0.033520
Montana       0.636978
Kentucky      0.692583
California    0.224892
Alabama      -0.018558
Indiana       0.436731
Montana       0.793141
Kentucky     -0.167263
California    1.899293
Alabama       1.469315
Indiana       0.623784
Montana       1.115197
Kentucky     -0.342214
California    0.314817
Alabama      -1.691182
Indiana       1.290790
Montana       0.191736
Kentucky      0.672414
California    0.374227
Alabama      -0.785702
Indiana      -0.227297
Montana    

Alabama      -0.140415
California    0.099503
Indiana       0.040353
Kentucky      0.071772
Montana      -0.030213
dtype: float64

In [111]:
indexed_series.describe()

count    50.000000
mean      0.008200
std       0.919523
min      -2.219293
25%      -0.496363
50%       0.007481
75%       0.663555
max       1.899293
dtype: float64

In [112]:
int_series.dtype

dtype('int64')

In [113]:
#Datetime index
dt_index = pd.date_range('2015-1-1', 
                        '2015-11-1', 
                        freq='m')
dt_series = pd.Series(randn(10), 
                      index = dt_index)
dt_series

2015-01-31    1.836583
2015-02-28    0.503168
2015-03-31    0.714811
2015-04-30   -0.381595
2015-05-31   -1.468504
2015-06-30   -0.329572
2015-07-31   -0.377992
2015-08-31    0.477226
2015-09-30   -0.501093
2015-10-31    0.205086
Freq: M, dtype: float64

In [114]:
#Datetime indexes make it easy to transform freqs etc!
dt_series.resample('q')

2015-03-31    1.018187
2015-06-30   -0.726557
2015-09-30   -0.133953
2015-12-31    0.205086
Freq: Q-DEC, dtype: float64

#DataFrames
Data frames extend the concept of Series to table-like data.

In [115]:
df = pd.DataFrame(randn(10, 5), index=dt_index, columns=["Dallas", "New York", "San Jose", "Denver", "Chicago"])
df.head(10)

Dallas  New York  San Jose    Denver   Chicago
2015-01-31 -1.716799  0.346554 -0.474599  0.501596 -1.152780
2015-02-28  0.815894 -0.174628  0.938712 -1.231667  0.480143
2015-03-31 -0.446962 -0.111780  1.111646 -0.212261  1.036505
2015-04-30 -0.062555 -0.184011  0.036399  0.651786  0.626042
2015-05-31 -1.203071 -1.641102 -0.951533  0.678304 -1.532163
2015-06-30 -1.042870  0.365829  0.420468  0.165601 -1.591016
2015-07-31 -0.894916 -0.774422 -1.429858  0.034182 -0.435324
2015-08-31 -0.206426  1.074492 -0.080327  0.243580 -1.074302
2015-09-30  1.033480  1.353700  1.629222 -1.272505 -2.328037
2015-10-31 -0.898834  0.674905  0.453633 -1.008496 -0.413906

In [116]:
type(df)

pandas.core.frame.DataFrame

In [117]:
type(df.Dallas)

pandas.core.series.Series

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 10 entries, 2015-01-31 00:00:00 to 2015-10-31 00:00:00
Freq: M
Data columns (total 5 columns):
Dallas      10 non-null float64
New York    10 non-null float64
San Jose    10 non-null float64
Denver      10 non-null float64
Chicago     10 non-null float64
dtypes: float64(5)
memory usage: 480.0 bytes


In [126]:
df.describe()

Dallas   New York   San Jose     Denver    Chicago
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   -0.462306   0.092954   0.165376  -0.144988  -0.638484
std     0.877745   0.880647   0.946533   0.761039   1.093550
min    -1.716799  -1.641102  -1.429858  -1.272505  -2.328037
25%    -1.006861  -0.181665  -0.376031  -0.809438  -1.437317
50%    -0.670939   0.117387   0.228434   0.099891  -0.754813
75%    -0.098523   0.597636   0.817442   0.437092   0.256631
max     1.033480   1.353700   1.629222   0.678304   1.036505

In [120]:
df.Denver.count()

10

In [121]:
df.dtypes

Dallas      float64
New York    float64
San Jose    float64
Denver      float64
Chicago     float64
dtype: object

In [122]:
df.index

<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-31, ..., 2015-10-31]
Length: 10, Freq: M, Timezone: None

In [123]:
df.columns = ["dallas", "New York", "San Jose", "denver", "Chicago"]

In [124]:
df = df.rename( columns= {'dallas': 'Dallas', 'denver': 'Denver'} )

In [125]:
df.sort(

SyntaxError: unexpected EOF while parsing (<ipython-input-125-ef33d7ba9342>, line 1)

#Selecting subsets.
There a couple of ways to select a subset of a python data frame.

In [ ]:
df[0:3]
# with row number

In [ ]:
df.Denver

In [ ]:
df.New York

In [ ]:
df["New York"]

In [ ]:
df[["New York", "Denver"]]

In [ ]:
df["new"] = df.Dallas + df.Denver

In [ ]:
df.head(7)

### Delete Column 

In [ ]:
y = df.pop("new")

In [ ]:
df.tail(4)

In [ ]:
y

In [ ]:
del df.Dallas

In [ ]:
del df["Dallas"]

In [ ]:
df.tail(7)

In [ ]:
df.index

In [ ]:
df.drop("Chicago")

In [ ]:
df.T

In [ ]:
df.head(4)

###Subset with conditions

In [ ]:
df[df["New York"]>0]

In [ ]:
df[df["New York"]>0 & df["Denver"]<0]

In [ ]:
df[(df["New York"]>0) & (df["Denver"]<0)]

In [ ]:
condition_1 = df["New York"]>0
condition_2 = df["Denver"]<0
df[condition_1 & condition_2]

In [ ]:
df[condition_1 | condition_2]

In [ ]:
df[!condition_1]

In [ ]:
df[~condition_1]

In [ ]:
df.query('~(Denver > 1 & Chicago <1)')

In [ ]:
df2["new"] = df.eval("Denver + Chicago")

In [ ]:
df.head(4)

#Advanced selection.
The above methods work for simple types of selections, but what if you need something more complex?

In [ ]:
df.loc['2015-05-31':'2015-08-31', 'Denver':'Chicago'] #Ranges by label.

In [ ]:
df.iloc[2:-3,2:5] #Ranges by number.

In [ ]:
df['state'] = ['Alabama', 'Alaska' , 'Arizona'] *10
df.head()

In [ ]:
df['state'] = ['Alabama', 'Alaska'] *5 
df.head()

In [ ]:
df = df.reset_index()

In [ ]:
df.head(3)

In [ ]:
df.index = df.state

In [ ]:
df.tail(3)

In [ ]:
df.index = df["index"]

In [ ]:
df.head(4)

In [ ]:
df = df.reset_index()

In [ ]:
df.head()

In [ ]:
df = df.set_index(['state', 'index'])
df.head()

In [ ]:
df.loc['Alabama'].head()

In [ ]:
df.head()

In [ ]:
df.ix[pd.to_datetime('2015-03-31')]
print df.index[0]

In [ ]:
df.ix[str(pd.to_datetime('2015-03-31'))]

In [ ]:
type(df.index)

In [ ]:
df.ix['Alabama']["Denver"]

In [ ]:
df.loc[('Alabama', '2015-01-31')] #Can do this.

#### .loc is primarily label based, but may also be used with a boolean array.

#### .iloc is primarily integer position based (from 0 to length-1 of the axis), but may also be used with a boolean array.

#### .ix supports mixed integer and label based access. It is primarily label based, but will fall back to integer positional access unless the corresponding axis is of integer type. .ix is the most general and will support any of the inputs in .loc and .iloc. .ix also supports floating point label schemes. .ix is exceptionally useful when dealing with mixed positional and label based hierachical indexes.

In [ ]:
df = df.reset_index()

In [ ]:
df = df.set_index("state")

In [ ]:
df.groupby("index").mean()

In [ ]:
df.columns = ["index_1", "level_0", "New York", "San Jose", "Denver","Chicago", "New"]

In [ ]:
df

In [ ]:
df.groupby(level=0).min()

In [ ]:
df["state"] = df.index

In [ ]:
df.index = df.index_1

In [ ]:
df.reset_index()

In [ ]:
df.head()

In [ ]:
del df["index_1"]

In [ ]:
df.reset_index()

In [ ]:
del df["level_0"]

In [ ]:
df.head(3)

### Groupby

In [ ]:
df.groupby(level=0)

In [ ]:
df = df.set_index(['state', 'index_1'])
df.groupby(level =0).mean().head()

In [ ]:
df.groupby(level=1).mean().head() #Groupby index

In [ ]:
df.reset_index().groupby('state').mean().head()

In [ ]:
g = df.groupby(level=0)

In [ ]:
g.aggregate(np.max)

In [ ]:
g.transform(lambda x: (x - x.mean())/x.std()).head()

In [ ]:
g.apply(lambda x: x.describe()).head(12)

In [ ]:
g.apply(lambda x: (x - x.mean())/x.std()).head()

In [ ]:
g.groups

In [ ]:
g.get_group("Alaska")

#Reading and writing data.


In [ ]:
df.to_csv(

In [ ]:
read = pd.read_('saved_data.csv', delimiter='\t')
#TONS OF options for reading data

In [ ]:
pd.read_csv(